"""crear tabla progreso

Revision ID: afe7ded8b3a3
Revises: 
Create Date: 2026-02-28 00:17:56.308664

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'afe7ded8b3a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('series_realizadas', sa.Integer(), nullable=True),
    sa.Column('reps_realizadas', sa.Integer(), nullable=True),
    sa.Column('peso_realizado', sa.Numeric(), nullable=True),
    sa.Column('notas_cliente', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():

    op.drop_table('progreso')
    # ### end Alembic commands ###